name: Main

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, Windows, x64, Runner1-AZR-EUS2W6375]
#     runs-on: [self-hosted, Linux, x64, Runner1]
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: |
          echo "==========Hello, world!=========="
          dir
          $PSVersionTable.PSVersion
          echo "==========Powershell version check done=========="
          [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
          echo "==========TLS certificate check done=========="
          dir
          

          echo "==========Downloading plugins=========="
          D:\GH-Runner1\JFR\jenkinsfile-runner-1.0-beta-30\bin\jenkinsfile-runner.bat -w D:\GH-Runner1\JFR\jenkins.war -p D:\GH-Runner1\JFR\plugins\plugins -f D:\GH-Runner1\_work\bai_test_jfr_compatibility\bai_test_jfr_compatibility\jenkinsfile -ns
          

          
#          .\jenkinsfile-runner-1.0-beta-30\bin\jenkinsfile-runner.bat -jv 2.359 -p D:\GH-Runner1\_work\bai_test_jfr_compatibility\bai_test_jfr_compatibility\plugins.txt -f D:\GH-Runner1\_work\bai_test_jfr_compatibility\bai_test_jfr_compatibility\jenkinsfile --mirror http://ftp.halifax.rwth-aachen.de/jenkins -ns
      
          
#          cp /home/runner/work/Test2/Test2/"${{ github.event.inputs.RepoName }}"/properties.jenkins /home/runner/work/Test2/Test2
#          ./bin/jenkinsfile-runner -w /application/actions-runner/Runner1/_work/JFR-test/JFR-test/jenkins.war -p /application/actions-runner/Runner1/_work/JFR-test/JFR-test/plugins.txt -f /application/actions-runner/Runner1/_work/JFR-test/JFR-test/jenkinsfile --mirror https://ftp.halifax.rwth-aachen.de/jenkins -ns
      
      
      
      
      #- name: Jenkinsfile Runner Prepackaged
      # You may pin to the exact commit or the version.
      # uses: jenkinsci/jenkinsfile-runner-github-actions@28b21582b55af29ca1e76329b0a48aa3843c5d
      #uses: jenkinsci/jenkinsfile-runner-github-actions@v0.2 
      #Invoke-WebRequest -UseBasicParsing \ 
      #https://github.com/jenkinsci/jenkinsfile-runner/releases/download/1.0-beta-30/jenkinsfile-runner-1.0-beta-30.zip \
      #-OutFile D:\GH-Runner1\_work\JFR-test\JFR-test\jenkinsfile-runner-1.0-beta-30.zip
#          echo "==========seeting up the download URL=========="
#          $env:JFR_Download_URL = 'https://github.com/jenkinsci/jenkinsfile-runner/releases/download/1.0-beta-30/jenkinsfile-runner-1.0-beta-30.zip'
#          echo echo "==========Downloading the zip file=========="
#          curl -o jenkinsfile-runner-1.0-beta-30.zip $env:JFR_Download_URL 
#          echo echo "==========Downloading the zip file=========="

#           echo "==========setting up the jenkins url=========="
#           $env:Jenkins_Download_URL = 'https://get.jenkins.io/war-stable/2.346.2/jenkins.war'
#           echo "==========Downloading the WAR file=========="
#           curl -o jenkins.war $env:Jenkins_Download_URL 
#           echo "==========downloaded the war file=========="
#           dir


#           echo "==========seting up the download url of JFR=========="
#           $env:JFR_Download_URL = 'https://github.com/jenkinsci/jenkinsfile-runner/releases/download/1.0-beta-30/jenkinsfile-runner-1.0-beta-30.zip'
#           echo "==========Downloading the JFR zip=========="
#           curl -o jenkinsfile-runner-1.0-beta-30.zip $env:JFR_Download_URL 
#           echo "==========unzipping the zip file=========="
#           Expand-Archive .\jenkinsfile-runner-1.0-beta-30.zip
#           echo "==========Unzipped the file=========="
#           dir



#           echo "==========setting up the jenkins url=========="
#           $env:Jenkins_Download_URL = 'https://get.jenkins.io/war-stable/2.346.2/jenkins.war'
#           echo "==========Downloading the WAR file=========="
#           curl -o jenkins.war $env:Jenkins_Download_URL 
#           echo "==========downloaded the war file=========="
#           dir
